### ISSUE TITLE
捉虫

### ISSUE THREAD

**Issue by LucunJi** [Xiaoyuan-xyz/The-Principle-of-Redstone-Circuits#1]
观察者那一章这个地方的的配图好像不对
> 例 3 拉杆拉下后，TNT能否爆炸？为什么？

另外如果是大量围绕同一主题的 markdown 文件的话 GitBook 可能是一个不错的发布方式。

**Comment by Xiaoyuan-xyz** [comment]
收到，已经更换了图片，会在下次更新刷新。
之后可能会考虑，还有可能考虑制作类似博客的想法，不过我个人也倾向于书，但可能需要我把相关的配置熟悉一下。
感谢支持。
